#include "cli.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <sys/stat.h>

#include "../forge/forge_generators.h"
#include "../core/active_migration.h"
#include "../db/db_create.h"
#include "../db/db_migrate.h"
#include "../action/action_dispatch.h"
#include "../action/action_controller.h"
#include "../action/action_router.h"
#include "../config/routes.h"

#include <unistd.h>

#ifndef CORTEX_VERSION
#define CORTEX_VERSION "0.0.0"
#endif

#ifndef CORTEX_SOURCE_ROOT
#define CORTEX_SOURCE_ROOT "."
#endif

static int ensure_dir_if_missing(const char *path) {
    if (mkdir(path, 0755) == -1 && errno != EEXIST) {
        return -1;
    }
    return 0;
}

static int has_suffix(const char *s, const char *suffix) {
    size_t ls;
    size_t lsf;
    if (!s || !suffix) return 0;
    ls = strlen(s);
    lsf = strlen(suffix);
    if (ls < lsf) return 0;
    return strcmp(s + (ls - lsf), suffix) == 0;
}

static const char *javascript_entrypoint_path(void) {
    if (access("app/javascript/application.jsx", F_OK) == 0) {
        return "app/javascript/application.jsx";
    }
    return "app/javascript/application.js";
}

static int ensure_frontend_dependencies_installed(void) {
    if (access("package.json", F_OK) != 0) {
        return 0;
    }
    if (access("node_modules/react/package.json", F_OK) == 0 &&
        access("node_modules/react-dom/package.json", F_OK) == 0 &&
        access("node_modules/esbuild/package.json", F_OK) == 0) {
        return 0;
    }
    printf("assets: installing frontend dependencies (react, react-dom, esbuild)\n");
    return system("npm install") == 0 ? 0 : -1;
}

static int write_controllers_registry(void) {
    DIR *dir;
    struct dirent *ent;
    FILE *f;
    int count = 0;

    if (ensure_dir_if_missing("app") != 0) return -1;
    if (ensure_dir_if_missing("app/javascript") != 0) return -1;
    if (ensure_dir_if_missing("app/javascript/controllers") != 0) return -1;

    dir = opendir("app/javascript/controllers");
    if (!dir) return -1;
    f = fopen("app/javascript/controllers/index.js", "w");
    if (!f) {
        closedir(dir);
        return -1;
    }

    fprintf(f, "/* Auto-generated by Cortex. Do not edit manually. */\n");
    while ((ent = readdir(dir)) != NULL) {
        const char *name = ent->d_name;
        size_t len = strlen(name);
        if (name[0] == '.') continue;
        if (!has_suffix(name, "_controller.js")) continue;
        if (strcmp(name, "index.js") == 0) continue;

        {
            char identifier[128];
            size_t base_len = len - strlen("_controller.js");
            if (base_len >= sizeof(identifier)) base_len = sizeof(identifier) - 1;
            memcpy(identifier, name, base_len);
            identifier[base_len] = '\0';
            fprintf(f, "import %sController from \"./%s\";\n", identifier, name);
            ++count;
        }
    }
    fprintf(f, "\nexport function registerControllers(application) {\n");
    if (count == 0) {
        fprintf(f, "  /* No controllers yet. */\n");
    } else {
        rewinddir(dir);
        while ((ent = readdir(dir)) != NULL) {
            const char *name = ent->d_name;
            size_t len = strlen(name);
            if (name[0] == '.') continue;
            if (!has_suffix(name, "_controller.js")) continue;
            if (strcmp(name, "index.js") == 0) continue;
            {
                char identifier[128];
                size_t base_len = len - strlen("_controller.js");
                if (base_len >= sizeof(identifier)) base_len = sizeof(identifier) - 1;
                memcpy(identifier, name, base_len);
                identifier[base_len] = '\0';
                fprintf(f, "  application.register(\"%s\", %sController);\n", identifier, identifier);
            }
        }
    }
    fprintf(f, "}\n");
    fclose(f);
    closedir(dir);
    return 0;
}

static int build_js_bundle(int watch_mode) {
    const char *mode_dir = watch_mode ? "development" : "production";
    const char *entry_names = watch_mode ? "application" : "application-[hash]";
    const char *sourcemap = watch_mode ? "--sourcemap" : "";
    const char *minify = watch_mode ? "" : "--minify";
    const char *watch = watch_mode ? "--watch" : "";
    char command[4096];

    if (ensure_frontend_dependencies_installed() != 0) {
        fprintf(stderr, "assets: failed to install frontend dependencies\n");
        return -1;
    }

    if (write_controllers_registry() != 0) {
        fprintf(stderr, "assets: failed to build controller registry\n");
        return -1;
    }
    if (ensure_dir_if_missing("public") != 0) return -1;
    if (ensure_dir_if_missing("public/assets") != 0) return -1;

    if (snprintf(command, sizeof(command),
                 "rm -f public/assets/application*.js public/assets/manifest.json && "
                 "npx esbuild %s --bundle --format=esm --outdir=public/assets --entry-names=%s %s %s %s && "
                 "node -e \"const fs=require('fs');const p='public/assets';const files=fs.readdirSync(p).filter(f=>/^application.*\\\\.js$/.test(f)).sort();const file=files[files.length-1]||'application.js';fs.writeFileSync(p+'/manifest.json',JSON.stringify({'application.js':file,environment:'%s'},null,2));\" && "
                 "(test -d app/assets && { mkdir -p public/assets && cp -R app/assets/. public/assets/; } || true)",
                 javascript_entrypoint_path(), entry_names, sourcemap, minify, watch, mode_dir) < 0) {
        return -1;
    }
    return system(command) == 0 ? 0 : -1;
}

int cli_parse(int argc, char **argv, CliParsed *out) {
    if (!out || argc < 2) {
        return -1;
    }

    out->command = CLI_COMMAND_NONE;
    out->name = NULL;
    out->attributes = NULL;
    out->attribute_count = 0;
    out->use_react = 1;

    /* argv[0] is the program name, argv[1] is the first word. */
    if (strcmp(argv[1], "--version") == 0 || strcmp(argv[1], "-v") == 0 || strcmp(argv[1], "version") == 0) {
        if (argc != 2) {
            return -1;
        }
        out->command = CLI_COMMAND_VERSION;
        return 0;
    }

    if (strcmp(argv[1], "server") == 0) {
        if (argc != 2) {
            return -1;
        }
        out->command = CLI_COMMAND_SERVER;
        return 0;
    }

    if (strcmp(argv[1], "new") == 0) {
        if (argc != 3) {
            return -1;
        }
        out->command = CLI_COMMAND_NEW;
        out->name = argv[2];
        return 0;
    }

    if (strcmp(argv[1], "generate") == 0 || strcmp(argv[1], "g") == 0) {
        if (argc < 3) {
            return -1;
        }

        /* Allow forms:
         *   cortex generate <name>                        (controller)
         *   cortex generate controller <name>            (controller)
         *   cortex generate resource <name>              (controller + views)
         *   cortex generate model <name>                 (model only)
         *   cortex generate service <name>               (service only)
         *   cortex generate neural:model <name>          (neural model starter)
         *   cortex generate neural:prompt <name>         (prompt module starter)
         *   cortex generate neural:agent <name>          (agent module starter)
         *   cortex generate neural:rag <name>            (RAG pipeline starter)
         *   cortex generate neural:stream <name>         (streaming module starter)
         *   cortex generate neural:memory <name>         (memory module starter)
         *   cortex generate neural:retriever <name>      (retrieval module starter)
         *   cortex generate neural:integration <name>    (provider adapter starter)
         *   cortex generate neural:policy <name>         (guardrails starter)
         *   cortex generate scaffold <Name> a:b c:d      (scaffold)
         */
        if (argc == 3) {
            out->command = CLI_COMMAND_GENERATE_CONTROLLER;
            out->name = argv[2];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "controller") == 0) {
            out->command = CLI_COMMAND_GENERATE_CONTROLLER;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "resource") == 0) {
            out->command = CLI_COMMAND_GENERATE_RESOURCE;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "model") == 0) {
            out->command = CLI_COMMAND_GENERATE_MODEL;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "service") == 0) {
            out->command = CLI_COMMAND_GENERATE_SERVICE;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:model") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_MODEL;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:prompt") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_PROMPT;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:agent") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_AGENT;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:rag") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_RAG;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:stream") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_STREAM;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:memory") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_MEMORY;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:retriever") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_RETRIEVER;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:integration") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_INTEGRATION;
            out->name = argv[3];
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "neural:policy") == 0) {
            out->command = CLI_COMMAND_GENERATE_NEURAL_POLICY;
            out->name = argv[3];
            return 0;
        }

        if (argc >= 5 && strcmp(argv[2], "scaffold") == 0) {
            int i;
            int attr_count = 0;
            int seen_flag = 0;
            const char **attributes;

            out->command = CLI_COMMAND_GENERATE_SCAFFOLD;
            out->name = argv[3]; /* resource name, e.g. Post */
            out->use_react = 1;
            attributes = (const char **)&argv[4];

            /* Validate tokens look like field or field:type.
             * When no type is provided, scaffold defaults to string.
             */
            for (i = 4; i < argc; ++i) {
                const char *tok = argv[i];
                const char *colon;

                if (!tok) return -1;
                if (strcmp(tok, "--react") == 0) {
                    out->use_react = 1;
                    seen_flag = 1;
                    continue;
                }
                if (strcmp(tok, "--no-react") == 0) {
                    out->use_react = 0;
                    seen_flag = 1;
                    continue;
                }
                if (seen_flag) {
                    return -1;
                }
                colon = strchr(tok, ':');
                if (colon == tok || (colon && colon[1] == '\0')) {
                    return -1;
                }
                ++attr_count;
            }

            if (attr_count <= 0) {
                return -1;
            }

            out->attributes = attributes;
            out->attribute_count = attr_count;
            return 0;
        }

        if (argc == 4 && strcmp(argv[2], "stimulus") == 0) {
            out->command = CLI_COMMAND_GENERATE_STIMULUS;
            out->name = argv[3];
            return 0;
        }

        return -1;
    }

    if (strcmp(argv[1], "db:migrate") == 0) {
        if (argc != 2) {
            return -1;
        }
        out->command = CLI_COMMAND_DB_MIGRATE;
        return 0;
    }

    if (strcmp(argv[1], "assets:build") == 0) {
        if (argc != 2) return -1;
        out->command = CLI_COMMAND_ASSETS_BUILD;
        return 0;
    }
    if (strcmp(argv[1], "dev") == 0) {
        if (argc != 2) return -1;
        out->command = CLI_COMMAND_DEV;
        return 0;
    }

    /* Allow the alternate form: `cortex db migrate`. */
    if (strcmp(argv[1], "db") == 0) {
        if (argc != 3) {
            return -1;
        }
        if (strcmp(argv[2], "migrate") == 0) {
            out->command = CLI_COMMAND_DB_MIGRATE;
            return 0;
        }
    }

    if (strcmp(argv[1], "db:create") == 0) {
        if (argc != 2) {
            return -1;
        }
        out->command = CLI_COMMAND_DB_CREATE;
        return 0;
    }

    /* Allow the alternate form: `cortex db create`. */
    if (strcmp(argv[1], "db") == 0) {
        if (argc != 3) {
            return -1;
        }
        if (strcmp(argv[2], "create") != 0) {
            return -1;
        }
        out->command = CLI_COMMAND_DB_CREATE;
        return 0;
    }

    return -1;
}

static int cli_handle_server(void) {
    /* If we are inside a generated project, delegate to project Makefile. */
    if (access(".cortex_project", F_OK) == 0 &&
        access("Makefile", F_OK) == 0 &&
        access("config/routes.c", F_OK) == 0) {
        char command[1024];
        int rc;
        printf("server: detected project mode\n");
        if (snprintf(command, sizeof(command), "CORTEX_ROOT=\"%s\" make server", CORTEX_SOURCE_ROOT) < 0) {
            fprintf(stderr, "server: failed to build project command\n");
            return -1;
        }
        rc = system(command);
        if (rc != 0) {
            fprintf(stderr, "server: failed to build/run project server\n");
            return -1;
        }
        return 0;
    }

    ActionRouter router;

    action_router_init(&router);
    register_routes(&router);

    printf("server: starting (listening until stopped)\n");
    printf("Listening on http://localhost:3000\n");
    printf("Use Ctrl-C to stop\n");
    return action_dispatch_serve_http(&router);
}

static int cli_handle_new(const char *project_name) {
    if (!project_name || project_name[0] == '\0') {
        return -1;
    }
    printf("new: creating project '%s'\n", project_name);
    int rc = forge_new_project(project_name);
    if (rc != 0) {
        fprintf(stderr, "failed to create project %s\n", project_name);
        return rc;
    }
    return 0;
}

static int cli_handle_generate_controller(const char *name) {
    if (!name || name[0] == '\0') {
        return -1;
    }
    printf("generate: creating controller '%s'\n", name);
    int rc = forge_generate_controller(name);
    if (rc != 0) {
        fprintf(stderr, "failed to generate controller for %s\n", name);
        return rc;
    }
    return 0;
}

static int cli_handle_generate_resource(const char *name) {
    if (!name || name[0] == '\0') {
        return -1;
    }
    printf("generate: creating resource '%s'\n", name);
    if (forge_generate_resource(name) != 0) {
        fprintf(stderr, "failed to generate resource for %s\n", name);
        return -1;
    }
    return 0;
}

static int cli_handle_generate_model(const char *name) {
    if (!name || name[0] == '\0') {
        return -1;
    }
    printf("generate: creating model '%s'\n", name);
    if (forge_generate_model(name) != 0) {
        fprintf(stderr, "failed to generate model for %s\n", name);
        return -1;
    }
    return 0;
}

static int cli_handle_generate_service(const char *name) {
    if (!name || name[0] == '\0') {
        return -1;
    }
    printf("generate: creating service '%s'\n", name);
    if (forge_generate_service(name) != 0) {
        fprintf(stderr, "failed to generate service for %s\n", name);
        return -1;
    }
    return 0;
}

static int cli_handle_generate_neural_model(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:model: creating '%s'\n", name);
    return forge_generate_neural_model(name);
}

static int cli_handle_generate_neural_prompt(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:prompt: creating '%s'\n", name);
    return forge_generate_neural_prompt(name);
}

static int cli_handle_generate_neural_agent(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:agent: creating '%s'\n", name);
    return forge_generate_neural_agent(name);
}

static int cli_handle_generate_neural_rag(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:rag: creating '%s'\n", name);
    return forge_generate_neural_rag(name);
}

static int cli_handle_generate_neural_stream(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:stream: creating '%s'\n", name);
    return forge_generate_neural_stream(name);
}

static int cli_handle_generate_neural_memory(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:memory: creating '%s'\n", name);
    return forge_generate_neural_memory(name);
}

static int cli_handle_generate_neural_retriever(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:retriever: creating '%s'\n", name);
    return forge_generate_neural_retriever(name);
}

static int cli_handle_generate_neural_integration(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:integration: creating '%s'\n", name);
    return forge_generate_neural_integration(name);
}

static int cli_handle_generate_neural_policy(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate neural:policy: creating '%s'\n", name);
    return forge_generate_neural_policy(name);
}

static int cli_handle_generate_scaffold(const char *name, int attr_count, const char **attributes, int use_react) {
    if (!name || name[0] == '\0') {
        return -1;
    }
    if (attr_count <= 0 || !attributes) {
        return -1;
    }

    printf("generate scaffold: creating '%s'\n", name);

    /* Debug: show current working directory so we know where files are generated. */
    {
        char cwd[1024];
        if (getcwd(cwd, sizeof(cwd)) != NULL) {
            printf("generate scaffold: cwd='%s'\n", cwd);
        }
    }

    return forge_generate_scaffold(name, attr_count, attributes, use_react);
}

static int cli_handle_generate_stimulus(const char *name) {
    if (!name || name[0] == '\0') return -1;
    printf("generate stimulus: creating '%s'\n", name);
    return forge_generate_stimulus_controller(name);
}

static int cli_handle_assets_build(void) {
    printf("assets:build: bundling JavaScript with esbuild\n");
    return build_js_bundle(0);
}

static int cli_handle_dev(void) {
    char command[4096];
    printf("dev: running JavaScript watcher and server\n");
    if (ensure_frontend_dependencies_installed() != 0) return -1;
    if (write_controllers_registry() != 0) return -1;
    if (ensure_dir_if_missing("public") != 0) return -1;
    if (ensure_dir_if_missing("public/assets") != 0) return -1;
    if (snprintf(command, sizeof(command),
                 "rm -f public/assets/application.js public/assets/manifest.json && "
                 "npx esbuild %s --bundle --format=esm --outfile=public/assets/application.js --sourcemap --watch >/tmp/cortex-js-watch.log 2>&1 & "
                 "node -e \"const fs=require('fs');const p='public/assets';fs.writeFileSync(p+'/manifest.json',JSON.stringify({'application.js':'application.js',environment:'development'},null,2));\"",
                 javascript_entrypoint_path()) < 0) {
        return -1;
    }
    if (system(command) != 0) return -1;
    return cli_handle_server();
}

static int cli_handle_db_migrate(void) {
    printf("db:migrate: running migrations\n");
    return db_migrate_default(NULL);
}

static int cli_handle_db_create(void) {
    printf("db:create: creating database (default SQLite for current environment)\n");
    return db_create(NULL);
}

static int cli_handle_version(void) {
    printf("cortex %s\n", CORTEX_VERSION);
    return 0;
}

int cli_dispatch(const CliParsed *parsed) {
    if (!parsed) {
        return -1;
    }

    switch (parsed->command) {
    case CLI_COMMAND_VERSION:
        return cli_handle_version();
    case CLI_COMMAND_SERVER:
        return cli_handle_server();
    case CLI_COMMAND_NEW:
        return cli_handle_new(parsed->name);
    case CLI_COMMAND_GENERATE_CONTROLLER:
        return cli_handle_generate_controller(parsed->name);
    case CLI_COMMAND_GENERATE_RESOURCE:
        return cli_handle_generate_resource(parsed->name);
    case CLI_COMMAND_GENERATE_MODEL:
        return cli_handle_generate_model(parsed->name);
    case CLI_COMMAND_GENERATE_SERVICE:
        return cli_handle_generate_service(parsed->name);
    case CLI_COMMAND_GENERATE_SCAFFOLD:
        return cli_handle_generate_scaffold(parsed->name, parsed->attribute_count, parsed->attributes, parsed->use_react);
    case CLI_COMMAND_GENERATE_NEURAL_MODEL:
        return cli_handle_generate_neural_model(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_PROMPT:
        return cli_handle_generate_neural_prompt(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_AGENT:
        return cli_handle_generate_neural_agent(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_RAG:
        return cli_handle_generate_neural_rag(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_STREAM:
        return cli_handle_generate_neural_stream(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_MEMORY:
        return cli_handle_generate_neural_memory(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_RETRIEVER:
        return cli_handle_generate_neural_retriever(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_INTEGRATION:
        return cli_handle_generate_neural_integration(parsed->name);
    case CLI_COMMAND_GENERATE_NEURAL_POLICY:
        return cli_handle_generate_neural_policy(parsed->name);
    case CLI_COMMAND_GENERATE_STIMULUS:
        return cli_handle_generate_stimulus(parsed->name);
    case CLI_COMMAND_DEV:
        return cli_handle_dev();
    case CLI_COMMAND_ASSETS_BUILD:
        return cli_handle_assets_build();
    case CLI_COMMAND_DB_MIGRATE:
        return cli_handle_db_migrate();
    case CLI_COMMAND_DB_CREATE:
        return cli_handle_db_create();
    default:
        return -1;
    }
}

int cli_run(int argc, char **argv) {
    CliParsed parsed;
    if (cli_parse(argc, argv, &parsed) != 0) {
        fprintf(stderr, "Usage:\n");
        fprintf(stderr, "  %s --version\n", argv[0]);
        fprintf(stderr, "  %s -v\n", argv[0]);
        fprintf(stderr, "  %s server\n", argv[0]);
        fprintf(stderr, "  %s new <project_name>\n", argv[0]);
        fprintf(stderr, "  %s generate <name>\n", argv[0]);
        fprintf(stderr, "  %s g <name>\n", argv[0]);
        fprintf(stderr, "  %s generate controller <name>\n", argv[0]);
        fprintf(stderr, "  %s g controller <name>\n", argv[0]);
        fprintf(stderr, "  %s generate resource <name>\n", argv[0]);
        fprintf(stderr, "  %s g resource <name>\n", argv[0]);
        fprintf(stderr, "  %s generate model <name>\n", argv[0]);
        fprintf(stderr, "  %s g model <name>\n", argv[0]);
        fprintf(stderr, "  %s generate service <name>\n", argv[0]);
        fprintf(stderr, "  %s g service <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:model <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:model <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:prompt <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:prompt <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:agent <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:agent <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:rag <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:rag <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:stream <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:stream <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:memory <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:memory <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:retriever <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:retriever <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:integration <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:integration <name>\n", argv[0]);
        fprintf(stderr, "  %s generate neural:policy <name>\n", argv[0]);
        fprintf(stderr, "  %s g neural:policy <name>\n", argv[0]);
        fprintf(stderr, "  %s generate stimulus <name>\n", argv[0]);
        fprintf(stderr, "  %s g stimulus <name>\n", argv[0]);
        fprintf(stderr, "  %s generate scaffold <Name> field:type field:type [--react|--no-react]\n", argv[0]);
        fprintf(stderr, "  %s g scaffold <Name> field:type field:type [--react|--no-react]\n", argv[0]);
        fprintf(stderr, "  %s assets:build\n", argv[0]);
        fprintf(stderr, "  %s dev\n", argv[0]);
        fprintf(stderr, "  %s db:migrate\n", argv[0]);
        fprintf(stderr, "  %s db:create\n", argv[0]);
        return -1;
    }
    return cli_dispatch(&parsed);
}

