-- Cortex schema dump (generated by db:migrate)
PRAGMA foreign_keys=OFF;
CREATE TABLE cortex_sql_migrations (
  name TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE schema_migrations (
  version INTEGER PRIMARY KEY NOT NULL
);
