-- Cortex schema dump (generated by db:migrate)
PRAGMA foreign_keys=OFF;
CREATE TABLE pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  created_at DATETIME,
  updated_at DATETIME
);

CREATE TABLE schema_migrations (
  version TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  applied_at TEXT DEFAULT CURRENT_TIMESTAMP
);
