#include "sql_migrate.h"

#include "db_migration_runner.h"
#include "db_migration_schema.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int db_sql_migrations_has_pending(DbConnection *conn, int *out_has_pending) {
    MigrationFile *files = NULL;
    size_t i;
    size_t n = 0;

    if (!conn || !out_has_pending) {
        return -1;
    }
    *out_has_pending = 0;

    if (db_migration_ensure_table(conn) != 0) {
        return -1;
    }

    if (db_migration_scan_directory(db_migration_default_directory(), &files, &n) != 0) {
        return -1;
    }

    for (i = 0; i < n; ++i) {
        int applied = 0;
        if (db_migration_is_applied(conn, files[i].version, &applied) != 0) {
            free(files);
            return -1;
        }
        if (!applied) {
            *out_has_pending = 1;
            free(files);
            return 0;
        }
    }

    free(files);
    return 0;
}

int db_sql_migrations_run(DbConnection *conn) {
    MigrationResult r;

    if (!conn) {
        return -1;
    }
    r = db_migration_migrate_sql_files(conn);
    return r.errors > 0 ? -1 : 0;
}

int db_schema_write_dump(DbConnection *conn, const char *schema_path) {
    DbStatement *st = NULL;
    FILE *out;
    int step;
    int first = 1;

    if (!conn || !schema_path) {
        return -1;
    }

    if (db_connection_backend(conn) == CORTEX_DB_BACKEND_POSTGRESQL) {
        /* sqlite_master-based dump is SQLite-specific; do not fail db:migrate. */
        return 0;
    }

    if (db_connection_prepare(
            conn,
            "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%%' "
            "ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name",
            &st) != 0) {
        return -1;
    }

    out = fopen(schema_path, "w");
    if (!out) {
        db_statement_finalize(st);
        fprintf(stderr, "db: cannot write %s\n", schema_path);
        return -1;
    }

    fputs("-- Cortex schema dump (generated by db:migrate)\n", out);
    fputs("PRAGMA foreign_keys=OFF;\n", out);

    for (;;) {
        step = db_statement_step(st);
        if (step == 0) {
            break;
        }
        if (step < 0) {
            fclose(out);
            db_statement_finalize(st);
            return -1;
        }
        {
            const char *sql = db_statement_column_text(st, 0);
            if (sql && sql[0]) {
                if (!first) {
                    fputc('\n', out);
                }
                first = 0;
                fputs(sql, out);
                fputs(";\n", out);
            }
        }
    }

    db_statement_finalize(st);
    if (fclose(out) != 0) {
        return -1;
    }
    return 0;
}
